// Regenerates src/components/ui/solar-icons.tsx from the Iconify API.
// Run from src/web: `node scripts/solar-icons.mjs`. Add a name to ICONS, run it, commit both files.
import { writeFileSync } from "node:fs";

// [Iconify name, component name]
const ICONS = [
  ["add-linear", "AddLine"],
  ["alt-arrow-down-linear", "AltArrowDownLine"],
  ["alt-arrow-right-linear", "AltArrowRightLine"],
  ["book-bold", "Book"],
  ["chat-round-dots-bold", "ChatRoundDots"],
  ["check-circle-linear", "CheckCircleLine"],
  ["close-circle-linear", "CloseCircleLine"],
  ["cloud-bold", "Cloud"],
  ["code-square-bold", "CodeSquare"],
  ["cpu-bolt-bold", "CpuBolt"],
  ["danger-triangle-bold", "DangerTriangle"],
  ["document-text-bold", "DocumentText"],
  ["documents-bold", "Documents"],
  ["global-bold", "Global"],
  ["hamburger-menu-linear", "HamburgerMenuLine"],
  ["key-bold", "Key"],
  ["laptop-bold", "Laptop"],
  ["letter-bold", "Letter"],
  ["lock-keyhole-minimalistic-bold", "Lock"],
  ["moon-bold", "Moon"],
  ["play-bold", "Play"],
  ["plug-circle-linear", "PlugCircleLine"],
  ["refresh-circle-bold", "RefreshCircle"],
  ["scale-bold", "Scale"],
  ["shield-check-bold", "ShieldCheck"],
  ["sun-2-bold", "Sun"],
  ["target-bold", "Target"],
  ["user-bold", "User"],
  ["database-bold", "Database"],
  ["eye-bold", "Eye"],
  ["server-bold", "Server"],
  ["programming-bold", "Programming"],
  ["users-group-rounded-bold", "UsersGroup"],
  ["bolt-bold", "Bolt"],
  ["layers-bold", "Layers"],
  ["tuning-2-bold", "Tuning"],
  ["download-minimalistic-bold", "Download"],
  ["chart-2-bold", "Chart"],
  ["shield-warning-bold", "ShieldWarning"],
  ["link-round-bold", "LinkRound"],
  ["file-text-bold", "FileText"],
];

const header = `/*
  Generated by scripts/solar-icons.mjs from the Iconify API. Do not edit by hand.

  Icons from the Solar set by 480 Design, licensed CC BY 4.0
  (https://creativecommons.org/licenses/by/4.0/); the credit is in the footer.
  Each draws in currentColor at 1em, so it takes its colour and size from the text around it.
*/
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;
export type IconComponent = (props: IconProps) => React.JSX.Element;

function svg(body: string) {
  return function Icon(props: IconProps) {
    return (
      <svg
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        aria-hidden="true"
        focusable="false"
        {...props}
        dangerouslySetInnerHTML={{ __html: body }}
      />
    );
  };
}
`;

const out = [header];
for (const [name, comp] of ICONS) {
  const res = await fetch(`https://api.iconify.design/solar.json?icons=${name}`);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const data = await res.json();
  const icon = data.icons?.[name];
  if (!icon) throw new Error(`${name}: not in the Solar set`);
  if ((icon.width ?? data.width ?? 24) !== 24 || (icon.height ?? data.height ?? 24) !== 24) {
    throw new Error(`${name}: not a 24x24 icon`);
  }
  out.push(`export const ${comp} = svg(${JSON.stringify(icon.body)});`);
}
writeFileSync(new URL("../src/components/ui/solar-icons.tsx", import.meta.url), out.join("\n") + "\n");
console.log(`wrote ${ICONS.length} icons`);
